namespace Atc.Kepware.Configuration.KepwareContracts.Connectivity;

internal class TagGroup
{
    /// <summary>
    /// The tag group name.
    /// </summary>
    [JsonPropertyName("common.ALLTYPES_NAME")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The tag group description.
    /// </summary>
    [MaxLength(255)]
    [JsonPropertyName("common.ALLTYPES_DESCRIPTION")]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// The number of tags assigned to this tag group.
    /// </summary>
    [JsonPropertyName("servermain.TAGGROUP_LOCAL_TAG_COUNT")]
    public int TagCountInGroup { get; set; }

    /// <summary>
    /// The number of tags assigned to this tag group and all child groups.
    /// </summary>
    [JsonPropertyName("servermain.TAGGROUP_TOTAL_TAG_COUNT")]
    public int TagCountInTree { get; set; }

    /// <summary>
    /// Indicates if the Tag Group was autogenerated.
    /// </summary>
    [JsonPropertyName("servermain.TAGGROUP_AUTOGENERATED")]
    public bool AutoGenerated { get; set; }

    public override string ToString()
        => $"{nameof(Name)}: {Name}, {nameof(Description)}: {Description}, {nameof(TagCountInGroup)}: {TagCountInGroup}, {nameof(TagCountInTree)}: {TagCountInTree}, {nameof(AutoGenerated)}: {AutoGenerated}";
}