namespace Atc.Kepware.Configuration.Contracts.Connectivity.Drivers.AbbTotalflow;

/// <summary>
/// Represents an ABB Totalflow meter group.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public sealed class AbbTotalflowMeterGroup : MeterGroupBase, IAbbTotalflowMeterGroup
{
}
