namespace Atc.Kepware.Configuration.KepwareContracts;

internal class TagGroup
{
    /// <summary>
    /// Specify the identity of this object.
    /// </summary>
    [JsonPropertyName("common.ALLTYPES_NAME")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Summary of this object or its use.
    /// </summary>
    [MaxLength(255)]
    [JsonPropertyName("common.ALLTYPES_DESCRIPTION")]
    public string Description { get; set; } = string.Empty;
}

////PROJECT_ID
////LocalTagCount int    `json:"servermain.TAGGROUP_LOCAL_TAG_COUNT"`
////TotalTagCount int    `json:"servermain.TAGGROUP_TOTAL_TAG_COUNT"`
////AutoGenerated bool   `json:"servermain.TAGGROUP_AUTOGENERATED"`