namespace Atc.Kepware.Configuration.KepwareContracts;

internal sealed class TagGroupRequest
{
}

//Name string `json:"common.ALLTYPES_NAME"`
//Description string `json:"common.ALLTYPES_DESCRIPTION"`
//AutoGenerated bool   `json:"servermain.TAGGROUP_AUTOGENERATED"`