namespace Atc.Kepware.Configuration.Contracts.Connectivity.Drivers.OmniFlowComputer;

/// <summary>
/// Represents an Omni Flow Computer meter group.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public sealed class OmniFlowComputerMeterGroup : MeterGroupBase, IOmniFlowComputerMeterGroup
{
}