namespace Atc.Kepware.Configuration.Contracts;

public sealed class TagGroup
{
    /// <summary>
    /// Specify the identity of this object.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Summary of this object or its use.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Indicates if the Tag Group was autogenerated.
    /// </summary>
    public bool AutoGenerated { get; set; }

    public IList<Tag> Tags { get; init; } = new List<Tag>();

    public IList<TagGroup> TagGroups { get; init; } = new List<TagGroup>();

    public override string ToString()
        => $"{nameof(Name)}: {Name}, {nameof(Description)}: {Description}, {nameof(AutoGenerated)}: {AutoGenerated}, {nameof(Tags)}.Count: {Tags?.Count}, {nameof(TagGroups)}.Count: {TagGroups?.Count}";
}