namespace Atc.Kepware.Configuration.Contracts.Connectivity.Drivers.FisherRocPlusEthernet;

/// <summary>
/// Represents a Fisher ROC Plus Ethernet meter group.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public sealed class FisherRocPlusEthernetMeterGroup : MeterGroupBase, IFisherRocPlusEthernetMeterGroup
{
}