namespace Atc.Kepware.Configuration.Contracts.Interfaces.Connectivity.AbbTotalflow;

/// <summary>
/// Interface for ABB Totalflow meter group objects.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public interface IAbbTotalflowMeterGroup : IMeterGroupBase
{
}
