namespace Atc.Kepware.Configuration.Contracts.Interfaces.Connectivity.FisherRocEthernet;

/// <summary>
/// Interface for Fisher ROC Ethernet meter group objects.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public interface IFisherRocEthernetMeterGroup : IMeterGroupBase
{
}