namespace Atc.Kepware.Configuration.Contracts.Interfaces.Connectivity.FisherRocPlusEthernet;

/// <summary>
/// Interface for Fisher ROC Plus Ethernet meter group objects.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public interface IFisherRocPlusEthernetMeterGroup : IMeterGroupBase
{
}