namespace Atc.Kepware.Configuration.Contracts.Interfaces.Connectivity;

/// <summary>
/// Base interface for meter group objects.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public interface IMeterGroupBase
{
    /// <summary>
    /// Name of the meter group.
    /// </summary>
    string Name { get; set; }

    /// <summary>
    /// Description of the meter group.
    /// </summary>
    string? Description { get; set; }
}
