namespace Atc.Kepware.Configuration.Contracts.Interfaces.Connectivity.OmniFlowComputer;

/// <summary>
/// Interface for Omni Flow Computer meter group objects.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public interface IOmniFlowComputerMeterGroup : IMeterGroupBase
{
}