namespace Atc.Kepware.Configuration.Contracts.Connectivity.Drivers.FisherRocEthernet;

/// <summary>
/// Represents a Fisher ROC Ethernet meter group.
/// </summary>
/// <remarks>
/// Meter groups are auto-generated by Kepware and cannot be created or deleted via API.
/// </remarks>
public sealed class FisherRocEthernetMeterGroup : MeterGroupBase, IFisherRocEthernetMeterGroup
{
}